baseURL: 'https://datamunch.tech'
title: DataMunch
paginate: 5
theme: hugo-PaperMod

#canonifyURLs: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false

googleAnalytics: G-97YG9JJHHH

minify:
  disableXML: true
  minifyOutput: true

disqusShortname: lamotte

params:
  ShowShareButtons: true
  ShowReadingTime: true
  comments: true
  homeInfoParams:
    Title: "A data science blog"
    Content: Wanderings in data science, data applications and data engineering.
  socialIcons:
    - name: github
      url: 'https://github.com/hlamotte'
    - name: linkedin
      url: 'https://www.linkedin.com/in/hamish-lamotte/'

#  params:
#  env: production # to enable google analytics, opengraph, twitter-cards and schema.
 # title: DataMunch
#  description: 'ExampleSite's description'
#  author: Me
#
#  #images: "<link or path of image for opengraph, twitter-cards>"
#
#  ShowReadingTime: true
#  ShowShareButtons: true
#  comments: true
#  disqusShortname: lamotte
#  defaultTheme: auto
#  disableThemeToggle : false
#  disableSpecial1stPost : false
#
#  #assets:
#  #  favicon: '<path / external url>'
#
#  label:
#    text: "Home"
#    icon: /apple-touch-icon.png
#    iconHeight: 35
#
#  # profile-mode
#  profileMode:
#    enabled: true # needs to be explicitly set
#    title: A data science blog
#    # imageUrl: '<img location>'
#    # imageTitle: my image
#    buttons:
#      - name: About
#        url: about
#      - name: Tags
#        url: tags
#      - name: Posts
#        url: posts

#
  # home-info mode
#  homeInfoParams:
#    Title: "A data science blog"
#    Content: Wanderings in data science, data applications and data engineering.
 #   Buttons:
 #     - name: About
 #       url: about
 #     - name: Tags
 #       url: tags
#
#  socialIcons:
#    - name: twitter
#      url: 'https://twitter.com/'
#    - name: linkedin
#      url: 'https://www.linkedin.com/in/hamish-lamotte/'
#    - name: github
#      url: 'https://github.com/hlamotte'
#
#
#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"

menu:
  main:
    - name: About
      weight: 1
      url: /about/