baseURL: 'https://datamunch.tech'
title: DataMunch
paginate: 5
theme: hugo-PaperMod

#canonifyURLs: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
#  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: DataMunch
#  description: 'ExampleSite's description'
#  author: Me
#
#  #images: "<link or path of image for opengraph, twitter-cards>"
#
  ShowReadingTime: true
  ShowShareButtons: true
  comments: true
  disqusShortname: lamotte
#  defaultTheme: auto
#  disableThemeToggle : false
#  disableSpecial1stPost : false
#
#  #assets:
#  #  favicon: '<path / external url>'
#
#  label:
#    text: "Home"
#    icon: /apple-touch-icon.png
#    iconHeight: 35
#
#  # profile-mode
#  profileMode:
#    enabled: false # needs to be explicitly set
#    title: ExampleSite
#    # imageUrl: '<img location>'
#    # imageTitle: my image
#    buttons:
#      - name: Posts
#        url: posts
#      - name: Tags
#        url: tags
#
  # home-info mode
  homeInfoParams:
    Title: "A data science blog"
    Content: Wanderings in data science, data applications and data engineering.
#
  socialIcons:
#    - name: twitter
#      url: 'https://twitter.com/'
    - name: linkedin
      url: 'https://www.linkedin.com/in/hamish-lamotte/'
    - name: github
      url: 'https://github.com/hlamotte'
#
#
#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"